/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.26
 * Generated at: 2014-07-18 11:04:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import model.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t\t\n");
      out.write("\t\t<title>Agenzia Immobiliare</title>\n");
      out.write("\t\t<link type=\"text/css\" rel=\"stylesheet\" href=\"css/style.css\">\n");
      out.write("\t\t<link rel=\"shortcut icon\" href=\"images/favicon.ico\" /> \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <div class=\"header\">\n");
      out.write("\t\n");
      out.write("\t\t<div id=\"menu\"> \n");
      out.write("\n");
      out.write("\t\t<div class=\"logo\"><h1><a href=\"./main\">Agenzia Immobiliare</a> </h1> </div>\n");
      out.write("\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t   <li><a href=\"./main\">Home</a></li>\n");
      out.write("\t\t\t   <li><a href=\"./main#chisiamo\">Chi siamo</a></li>\n");
      out.write("\t\t\t   <li><a href=\"./main#invendita\">Cerco casa</a></li>\n");
      out.write("\t\t\t   <li class=\"no_bg ped\"><a href=\"./main#contactus\">Dove siamo</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div> <!-- end menu-->\t\n");
      out.write("\t\t\n");
      out.write("\t</div> <!-- end header-->\n");
      out.write("\n");
      out.write("\t<div class=\"content\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"container\">\n");
      out.write("   \t\t  <div id=\"chisiamo\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t<div class=\"titolo\"><h2>Presentazione dell'azienda</h2></div>\n");
      out.write("\n");
      out.write("\t\t\t<div id=\"puntina1\"> <img src= \"images/tack.png\" width=\"100\" height=\"100\" ></div>\n");
      out.write("\t\t\t<div id=\"puntina2\"> <img src= \"images/tack.png\" width=\"100\" height=\"100\" ></div>\t\t\t\t\n");
      out.write("\t\t\t<div id=\"puntina3\"> <img src= \"images/tack.png\" width=\"100\" height=\"100\" ></div>\n");
      out.write("\n");
      out.write("\t\t<div id=\"two-columns\">\n");
      out.write("\t\t\t<div id=\"col1\">\n");
      out.write("\t\t\t   <h4> Il rapporto personale con i nostri clienti ci distingue. <br> Abbiamo a cuore le loro necessit&agrave e cerchiamo con insistenza di trovare la soluzione che risponda ai loro desideri in ogni dettaglio in tutti i casi. <br> I nostri clienti che desiderano una consulenza possono sempre contare sulla nostra disponibilit&agrave, professionalit&agrave, cordialit&agrave e riservatezza che consentono alla nostra agenzia di soddisfare il cliente in ogni fase della trattativa. <br>L'agenzia Immobiliare &egrave presente nella realta' del mercato immobiliare con immobili residenziali e commerciali nella provincia del Verbano, vero core business della societ&agrave oltre che in alcune localit&agrave turistiche pi&ugrave esclusive.<br> \n");
      out.write("Siamo sempre pi&ugrave convinti dell'importanza della collaborazione tra colleghi.<br> Il cliente che ci affida l'incarico per vendere il proprio immobile pu&ograve contare non solo sul nostro impegno, ma anche sulla collaborazione di altre agenzie operanti nella stessa zona e non, mantenendo comunque sempre l'agenzia immobiliare come unico interlocutore e referente in tutte le fasi della trattativa. </h4><br></div>\n");
      out.write("<div id=\"col2\"><h4>\n");
      out.write("La  nostra agenzia ha deciso di impegnare parte delle proprie risorse economiche nella pubblicit&agrave degli immobili, ben sapendo che una buona pubblicit&agrave &egrave garanzia di successo. <br> Per questo motivo ha scelto di pubblicizzare gli immobili acquisiti nelle pagine di riviste specializzate, nei portali di maggior riscontro, nel volantinaggio, per proporre gli immobili a chi ci lascia la propria richiesta. <br> Tutto questo a costi decisamente superiori alla media, ma l'esperienza infatti insegna che chi &egrave interessato alla vendita della propria casa vuole che la propria inserzione sia di facile ed immediato approccio, in modo da avere una rosa pi&ugrave ampia possibile di potenziali acquirenti, cos&igrave come eventuali acquirenti desiderano trovare il giusto affare con il minor dispendio di energia, tempo ed a prezzo equo. </h4>\n");
      out.write("</div></div>\n");
      out.write("\t\t</div> <!-- chi siamo end-->\n");
      out.write("\t     </div> <!-- container end -->\n");
      out.write("\t\n");
      out.write("\t    <div class=\"container\">\n");
      out.write("\t\t<div id=\"invendita\">\n");
      out.write("\n");
      out.write("\t\t\t<div class=\"titolo\"><h2> In vendita oggi: </h2></div>\n");
      out.write("\n");
      out.write("\t\t\t<h3>Elenco tipi di immobile per i quali esistono offerte di vendita  ( pu&ograve essere anche vuoto) </h3>\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");


    Integer nVillette = (Integer) request.getAttribute("numVillette1");
    Integer nVille = (Integer) request.getAttribute("numVille1");
    Integer nAppartamenti = (Integer) request.getAttribute("numAppartamenti1");
    

    if(nVillette==0 && nVille==0 && nAppartamenti==0)
   {  

    
      out.write("\t\t\n");
      out.write("            <h3><ul> Oggi non ci sono immobili in vendita. </ul></h3>\n");
      out.write("\n");

     } else {

      out.write("\n");
      out.write("    \n");
      out.write("            <h3><ul> In vendita oggi: <u>\n");
      out.write("\t\t\t   ");
if(nVillette!=0) {
                    String link = "./main?ps=villetta a schiera"; 
      out.write("\n");
      out.write("                    <li><a href=\"");
      out.print( link );
      out.write("\">Villetta a schiera ");
      out.print( nVillette );
      out.write("</a></li>\n");
      out.write("                                             ");
}
      out.write("\n");
      out.write("\t\t\t   ");
if(nVille!=0) {
                    String link = "./main?ps=villa singola"; 
      out.write("\n");
      out.write("                    <li><a href=\"");
      out.print( link );
      out.write("\">Villa singola ");
      out.print( nVille );
      out.write("</a></li>\n");
      out.write("                                             ");
}
      out.write("\n");
      out.write("\t\t\t   ");
if(nAppartamenti!=0) {
                    String link = "./main?ps=appartamento in palazzina"; 
      out.write("\n");
      out.write("                    <li><a href=\"");
      out.print( link );
      out.write("\">Appartamento in palazzina ");
      out.print( nAppartamenti );
      out.write("</a></li> \n");
      out.write("                                             ");
}
      out.write("\n");
      out.write("\t\t\t</u></ul><h3>\n");
      out.write("\n");
 } //fine else relativo all'esistenza o meno di immobili in vendita 
      out.write("\n");
      out.write("\n");
      out.write("           \n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t</div> <!-- invendita end-->\n");
      out.write("\t     </div> <!-- container end -->\n");
      out.write("\n");
      out.write("\t     <div class=\"container\">\n");
      out.write("\t\t<div id=\"contactus\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"titolo\"><h2>Sede dell'azienda e contatti</h2></div>\n");
      out.write("\n");
      out.write("\t\t\t<center>\n");
      out.write("\t\t\t\t    <iframe width=\"425\" height=\"350\" frameborder=\"0\"\n");
      out.write("\t\t\t\t    scrolling=\"no\" marginheight=\"0\" marginwidth=\"0\"\n");
      out.write("src=\"https://maps.google.it/maps?f=q&amp;source=s_q&amp;hl=it&amp;geocode=&amp;q=via+golino+verona&amp;aq=&amp;sll=45.421646,10.986046&amp;sspn=0.0694,0.156898&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Golino,+Verona&amp;t=m&amp;z=14&amp;ll=45.402224,10.9909&amp;output=embed\"></iframe> <br /><small><a\n");
      out.write(" href=\"https://maps.google.it/maps?f=q&amp;source=embed&amp;hl=it&amp;geocode=&amp;q=via+golino+verona&amp;aq=&amp;sll=45.421646,10.986046&amp;sspn=0.0694,0.156898&amp;ie=UTF8&amp;hq=&amp;hnear=Via+Golino,+Verona&amp;t=m&amp;z=14&amp;ll=45.402224,10.9909\" style=\"color:#0000FF;text-align:left\"></a></small>\n");
      out.write("\t\t\t</center>\n");
      out.write("\n");
      out.write("\t\t\t <h3> \n");
      out.write("\t\t\t\t<ul>\t\n");
      out.write("\t\t\t\t\t<li>Affiliato: \"C&agrave Vignal Case Sas\" </li>\n");
      out.write("\t\t\t\t\t<li>Responsabile: Eugenio Turri </li>\n");
      out.write("\t\t\t\t\t<li>Indirizzo: Via Golino 37b Verona </li>\n");
      out.write("\t\t\t\t\t<li>Recapito telefonico: 045 / 907 302</li>\n");
      out.write("\t\t\t\t</ul> \n");
      out.write("\t\t\t </h3>\n");
      out.write("\n");
      out.write("\t\t</div> <!-- contactus-->\n");
      out.write("\t    </div> <!-- container end -->\n");
      out.write("\t</div>\t<!-- content-end-->\n");
      out.write("\t\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("\t<h3> Progetto prodotto da Pietro Musoni e Carlo Tacchella. Corso di Base di dati. Anno 2013/2014.</h3>\n");
      out.write("</footer>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
